
name: actions-notify-stars
description: Notify Discord on Star

inputs:
  DISCORD_WEBHOOK_URL:
    required: true

  REPOSITORY:
    required: true

  ACTOR:
    required: true

runs:
  using: composite
  steps:
    - name: Send Discord Notification
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
          "content": "🌟 Repository `${{ inputs.REPOSITORY }}` just got a new star!",
          "embeds": [{
            "title": "New Star",
            "description": "Repository `${{ inputs.REPOSITORY }}` received a star from `${{ inputs.ACTOR_USERNAME }}`.\n\nThe repository now has `${{ inputs.STAR_COUNT }}` total stars!",
            "thumbnail": {
              "url": "${{ inputs.ACTOR_AVATAR_URL }}"
            }
          }]
        }' \
        "${{ inputs.DISCORD_WEBHOOK_URL }}"
      shell: bash