
name: actions-notify-stars
description: Notify Discord on Star

inputs:
  DISCORD_WEBHOOK_URL:
    required: true

  GITHUB_EVENT:
    required: true

runs:
  using: composite
  steps:
    - name: Send Discord Notification
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
          "content": "🌟 Repository `${{ inputs.GITHUB_EVENT.repository.name }}` just got a new star!",
          "username": "${{ inputs.GITHUB_EVENT.sender.login }}",
          "avatar_url": "${{ inputs.GITHUB_EVENT.sender.avatar_url }}"
          "embeds": [
            {
              "url": "${{ inputs.GITHUB_EVENT.sender.html_url }}"
            }
          ]
        }' \
        "${{ inputs.DISCORD_WEBHOOK_URL }}"
      shell: bash