
name: actions-notify-stars
description: Notify Discord on Star

inputs:
  DISCORD_WEBHOOK_URL:
    required: true

  REPOSITORY:
    required: true

  ACTOR:
    required: true

runs:
  using: composite
  steps:
    - name: Send Discord Notification
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"content": "🌟 The repository `${{ inputs.REPOSITORY }}` just got a new star from `${{ inputs.ACTOR }}`!"}' \
        "${{ inputs.DISCORD_WEBHOOK_URL }}"