
name: actions-notify-stars
description: Notify Discord on Star

inputs:
  DISCORD_WEBHOOK_URL:
    required: true

  GITHUB_REPOSITORY:
    required: true

  GITHUB_SENDER_LOGIN:
    required: true

  GITHUB_SENDER_AVATAR_URL:
    required: true

  GITHUB_SENDER_HTML_URL:
    required: true

runs:
  using: composite
  steps:
    - name: Send Discord Notification
      run: |
        REQUEST_BODY='{
          "content": "🌟 Repository `${{ inputs.GITHUB_REPOSITORY }}` just got a new star!",
          "username": "${{ inputs.GITHUB_SENDER_LOGIN }}",
          "avatar_url": "${{ inputs.GITHUB_SENDER_AVATAR_URL }}",
          "embeds": [
            {
              "title": "${{ inputs.GITHUB_SENDER_LOGIN }}",
              "url": "${{ inputs.GITHUB_SENDER_HTML_URL }}",
              "image": "${{ inputs.GITHUB_SENDER_AVATAR_URL }}"
            }
          ]
        }'

        echo "Request body: $REQUEST_BODY"

        curl -X POST -H "Content-Type: application/json" \
        -d "$REQUEST_BODY" \
        "${{ inputs.DISCORD_WEBHOOK_URL }}"
      shell: bash