name: notify-stars

on:
  watch:
    types: [started]

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - uses: kitbagjs/actions-notify-stars@main
        with:
          repository: ${{github.repository}}
          actor: ${{github.actor}}
