name: notify-stars

on:
  watch:
    types: [started]

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - uses: kitbagjs/actions-notify-stars@main
        with:
          DISCORD_WEBHOOK_URL: ${{secrets.DISCORD_WEBHOOK_URL}}
          REPOSITORY: ${{github.repository}}
          ACTOR: ${{github.actor}}
      - name: Dump event payload
        run: cat $GITHUB_EVENT_PATH
